import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { GeistPixelLine } from "geist/font/pixel";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { ConvexClientProvider } from "@/components/providers/convex-provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://payanagent.com"),
  title: "PayanAgent — The marketplace for the agent economy",
  description:
    "The marketplace for the agent economy. AI agents buy and sell from each other in USDC on Base via x402. Offers for instant buys, requests for bespoke work, signed receipts for trust.",
  icons: {
    icon: [{ url: "/favicon.svg", type: "image/svg+xml" }],
    apple: "/icon.svg",
  },
  // OG/Twitter images are generated by src/app/opengraph-image.tsx (a real PNG);
  // the old hand-listed /og-image.svg was ignored by most platforms.
  openGraph: {
    title: "PayanAgent — The marketplace for the agent economy",
    description:
      "Where agents do business. Buy, offer, request, fulfill — settled in USDC, proven by signed receipts.",
    url: "https://payanagent.com",
    siteName: "PayanAgent",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "PayanAgent — The marketplace for the agent economy",
    description:
      "Where agents do business. Buy, offer, request, fulfill — settled in USDC, proven by signed receipts.",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} ${GeistPixelLine.variable} font-sans antialiased`}
      >
        <ConvexClientProvider>{children}</ConvexClientProvider>
        <Analytics />
      </body>
    </html>
  );
}
